import js from "@eslint/js";
import prettier from "eslint-config-prettier";
import globals from "globals";
import tseslint from "typescript-eslint";

/**
 * Import boundaries.
 *
 * These are the security-relevant ones. `@hoodstack/server` and
 * `@hoodstack/database` can hold privileged credentials; anything reaching them
 * from a package that ships to a browser would put a server secret in a client
 * bundle. Convention does not prevent that - a lint error does.
 */
export const browserSafeBoundaries = {
  files: ["**/*.{ts,tsx}"],
  rules: {
    "no-restricted-imports": [
      "error",
      {
        patterns: [
          {
            group: ["@hoodstack/server", "@hoodstack/server/*"],
            message:
              "Browser-safe packages must not import @hoodstack/server. It may hold " +
              "privileged credentials that must never reach a client bundle.",
          },
          {
            group: ["@hoodstack/database", "@hoodstack/database/*"],
            message:
              "Browser-safe packages must not import @hoodstack/database. Database " +
              "access belongs behind the API.",
          },
          {
            group: ["node:*", "fs", "path", "crypto", "child_process"],
            message:
              "Browser-safe packages must not import Node built-ins. Use a web-standard " +
              "API, or move this code to a server package.",
          },
        ],
      },
    ],
  },
};

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/.next/**",
      "**/.turbo/**",
      "**/coverage/**",
      "**/node_modules/**",
      "**/*.config.{js,ts,mjs}",
      // Generated by Next.js on every build and overwritten; linting it just
      // produces an error nobody can fix.
      "**/next-env.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      // Unused variables are usually a mistake; an underscore prefix is the
      // explicit way to say "intentionally unused".
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // `any` erases the type safety this codebase depends on for correctness
      // around money and chain data.
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      // Swallowing a rejection in transaction code loses the failure entirely.
      "no-console": ["warn", { allow: ["warn", "error"] }],
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-param-reassign": "error",
    },
  },
  {
    // Tests may reach for shapes that production code should not.
    files: ["**/*.test.{ts,tsx}", "**/testing/**"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "no-console": "off",
    },
  },
  prettier,
);
